### ISSUE TITLE
Links of Readme is unavailable

### ISSUE THREAD

**Issue by pyanne2000** [MGI-tech-bioinformatics/DNBelab_C_Series_scRNA-analysis-software#1]
Hi, there are some environments that should be manually installed in your readme. However, the link you provided is unavailabe.

**Comment by pyanne2000** [comment]
It's Java which is unavailable.

**Comment by MGI-tech-bioinformatics** [comment]
Hi, I'm so sorry for the confusion. The link failure problem has been fixed.
