### ISSUE TITLE
No dropletUtils packages

### ISSUE THREAD

**Issue by pyanne2000** [MGI-tech-bioinformatics/DNBelab_C_Series_scRNA-analysis-software#2]
Hi, I can't install dropletutils packages in my R.studio? I am wondering if it's my problem or it was a misunderstanding?

**Comment by MGI-tech-bioinformatics** [comment]
Use Bioconductor to install dropletutils. See https://www.bioconductor.org/packages/release/bioc/html/DropletUtils.html

**Comment by pyanne2000** [comment]
I think it would be better if you give the users a clearer instruction, because installation of packages directly in shell is preferred by lots of people.

**Comment by MGI-tech-bioinformatics** [comment]
For the Third-party software, please refer to the manual of the third-party software.
