### ISSUE TITLE
demo file download fail

### ISSUE THREAD

**Issue by Lix1993** [MGI-tech-bioinformatics/DNBelab_C_Series_scRNA-analysis-software#5]

**Comment by Lix1993** [comment]
Demo.human.fq.1.gz Failed - File incomplete

**Comment by Lix1993** [comment]
Besides, could you provide a direct download url to download in linux server using wget.

**Comment by MGI-tech-bioinformatics** [comment]
Thank you for contacting us.
We have update demo file download link, please try to download via OneDrive.

**Comment by Lix1993** [comment]
Thanks, it can be download using chrome now.

The file in pan.genomics.cn ,cannot be downloaded using chrome, can be downloaded using free download manager and they a exactly the same file.
